### PR TITLE
Add upgrade jobs starting from Pulp 2.10

### PR DESCRIPTION
**Pull request by elyezer**
The current set of jobs are:

```
pulp-upgrade-2.10-stable-2.10-beta-f23
pulp-upgrade-2.10-stable-2.10-beta-rhel6
pulp-upgrade-2.10-stable-2.10-beta-rhel7
pulp-upgrade-2.10-stable-2.10-nightly-f23
pulp-upgrade-2.10-stable-2.10-nightly-rhel6
pulp-upgrade-2.10-stable-2.10-nightly-rhel7
pulp-upgrade-2.10-stable-2.11-nightly-f23
pulp-upgrade-2.10-stable-2.11-nightly-rhel6
pulp-upgrade-2.10-stable-2.11-nightly-rhel7
pulp-upgrade-2.8-stable-2.10-beta-f23
pulp-upgrade-2.8-stable-2.10-beta-rhel6
pulp-upgrade-2.8-stable-2.10-beta-rhel7
pulp-upgrade-2.8-stable-2.10-nightly-f23
pulp-upgrade-2.8-stable-2.10-nightly-rhel6
pulp-upgrade-2.8-stable-2.10-nightly-rhel7
pulp-upgrade-2.8-stable-2.11-nightly-f23
pulp-upgrade-2.8-stable-2.11-nightly-rhel6
pulp-upgrade-2.8-stable-2.11-nightly-rhel7
pulp-upgrade-2.8-stable-2.8-beta-f23
pulp-upgrade-2.8-stable-2.8-beta-rhel6
pulp-upgrade-2.8-stable-2.8-beta-rhel7
pulp-upgrade-2.8-stable-2.8-nightly-f23
pulp-upgrade-2.8-stable-2.8-nightly-rhel6
pulp-upgrade-2.8-stable-2.8-nightly-rhel7
pulp-upgrade-2.8-stable-2.9-beta-f23
pulp-upgrade-2.8-stable-2.9-beta-rhel6
pulp-upgrade-2.8-stable-2.9-beta-rhel7
pulp-upgrade-2.8-stable-2.9-nightly-f23
pulp-upgrade-2.8-stable-2.9-nightly-rhel6
pulp-upgrade-2.8-stable-2.9-nightly-rhel7
pulp-upgrade-2.9-stable-2.10-beta-f23
pulp-upgrade-2.9-stable-2.10-beta-rhel6
pulp-upgrade-2.9-stable-2.10-beta-rhel7
pulp-upgrade-2.9-stable-2.10-nightly-f23
pulp-upgrade-2.9-stable-2.10-nightly-rhel6
pulp-upgrade-2.9-stable-2.10-nightly-rhel7
pulp-upgrade-2.9-stable-2.11-nightly-f23
pulp-upgrade-2.9-stable-2.11-nightly-rhel6
pulp-upgrade-2.9-stable-2.11-nightly-rhel7
pulp-upgrade-2.9-stable-2.9-beta-f23
pulp-upgrade-2.9-stable-2.9-beta-rhel6
pulp-upgrade-2.9-stable-2.9-beta-rhel7
pulp-upgrade-2.9-stable-2.9-nightly-f23
pulp-upgrade-2.9-stable-2.9-nightly-rhel6
pulp-upgrade-2.9-stable-2.9-nightly-rhel7
```

### CODE REVIEW

**Comment by Ichimonji10** [comment]
LGTM

**Comment by preethit** [comment]
@elyezer 
I think we can remove considering the fact that there is not going to be another 2.9.z as per a recent email.
pulp-upgrade-2.9-stable-2.9-beta-f23
pulp-upgrade-2.9-stable-2.9-beta-rhel6
pulp-upgrade-2.9-stable-2.9-beta-rhel7
pulp-upgrade-2.9-stable-2.9-nightly-f23
pulp-upgrade-2.9-stable-2.9-nightly-rhel6
pulp-upgrade-2.9-stable-2.9-nightly-rhel7

**Comment by preethit** [comment]
@elyezer This can be removed as well.

pulp-upgrade-2.8-stable-2.8-beta-f23
pulp-upgrade-2.8-stable-2.8-beta-rhel6
pulp-upgrade-2.8-stable-2.8-beta-rhel7
pulp-upgrade-2.8-stable-2.8-nightly-f23
pulp-upgrade-2.8-stable-2.8-nightly-rhel6
pulp-upgrade-2.8-stable-2.8-nightly-rhel7
pulp-upgrade-2.8-stable-2.9-beta-f23
pulp-upgrade-2.8-stable-2.9-beta-rhel6
pulp-upgrade-2.8-stable-2.9-beta-rhel7
pulp-upgrade-2.8-stable-2.9-nightly-f23
pulp-upgrade-2.8-stable-2.9-nightly-rhel6
pulp-upgrade-2.8-stable-2.9-nightly-rhel7

**Comment by elyezer** [comment]
Update:

```
pulp-upgrade-2.10-stable-2.10-beta-f23
pulp-upgrade-2.10-stable-2.10-beta-rhel6
pulp-upgrade-2.10-stable-2.10-beta-rhel7
pulp-upgrade-2.10-stable-2.10-nightly-f23
pulp-upgrade-2.10-stable-2.10-nightly-rhel6
pulp-upgrade-2.10-stable-2.10-nightly-rhel7
pulp-upgrade-2.10-stable-2.11-nightly-f23
pulp-upgrade-2.10-stable-2.11-nightly-rhel6
pulp-upgrade-2.10-stable-2.11-nightly-rhel7
pulp-upgrade-2.8-stable-2.10-beta-f23
pulp-upgrade-2.8-stable-2.10-beta-rhel6
pulp-upgrade-2.8-stable-2.10-beta-rhel7
pulp-upgrade-2.8-stable-2.10-nightly-f23
pulp-upgrade-2.8-stable-2.10-nightly-rhel6
pulp-upgrade-2.8-stable-2.10-nightly-rhel7
pulp-upgrade-2.8-stable-2.11-nightly-f23
pulp-upgrade-2.8-stable-2.11-nightly-rhel6
pulp-upgrade-2.8-stable-2.11-nightly-rhel7
pulp-upgrade-2.9-stable-2.10-beta-f23
pulp-upgrade-2.9-stable-2.10-beta-rhel6
pulp-upgrade-2.9-stable-2.10-beta-rhel7
pulp-upgrade-2.9-stable-2.10-nightly-f23
pulp-upgrade-2.9-stable-2.10-nightly-rhel6
pulp-upgrade-2.9-stable-2.10-nightly-rhel7
pulp-upgrade-2.9-stable-2.11-nightly-f23
pulp-upgrade-2.9-stable-2.11-nightly-rhel6
pulp-upgrade-2.9-stable-2.11-nightly-rhel7
```

**Comment by preethit** [comment]
LGTM

**Comment by Ichimonji10** [comment]
:tada:

**Pull request merged**
