### PR TITLE
Add a copyright to the repository.

### PR DESCRIPTION
**Pull request by rbarlow**

### CODE REVIEW

**Comment by elyezer** [comment]
#146 already add this.

**Comment by rbarlow** [comment]
On Thu, May 05, 2016 at 12:37:11PM -0700, Elyézer Rezende wrote:
> #146 already add this. 


True, but this PR adds it to the f23 branch, which will diverge from the
master branch.

-- 
Randy Barlow
irc:   bowlofeggs

**Comment by elyezer** [comment]
Did not realized that. Thanks for the clarification.

**Comment by rbarlow** [comment]
I created a new repository to hold the f23 stuff, so I'm closing this. See https://github.com/pulp/packaging

**Pull request closed without merging**
