### PR TITLE
Add Ansible role to install Pulp Crane

### PR DESCRIPTION
**Pull request by Ichimonji10**
Make the `pulp_server.yaml` playbook call the new Ansible role,
"pulp-crane."

### CODE REVIEW

**Comment by Ichimonji10** [comment]
This PR is marked as DO NOT MERGE because of [Pulp issue 2719](https://pulp.plan.io/issues/2719). As soon as that issue is fixed, this PR will become viable.

**Comment by Ichimonji10** [comment]
In a previous version of this PR, I had expanded the `pulp-smash` role to also install, start and enable docker. However, Docker is broken out of the box on Fedora 25 and RHEL 7 due to this gem:

```console
# systemctl --state failed
  UNIT                         LOAD   ACTIVE SUB    DESCRIPTION
● docker-storage-setup.service loaded failed failed Docker Storage Setup

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
# systemctl status docker-storage-setup
● docker-storage-setup.service - Docker Storage Setup
   Loaded: loaded (/usr/lib/systemd/system/docker-storage-setup.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-04-17 16:36:06 EDT; 1min 18s ago
  Process: 30308 ExecStart=/usr/bin/docker-storage-setup (code=exited, status=1/FAILURE)
 Main PID: 30308 (code=exited, status=1/FAILURE)

Apr 17 16:36:06 fedora-25-pulp-2-13 systemd[1]: Starting Docker Storage Setup...
Apr 17 16:36:06 fedora-25-pulp-2-13 docker-storage-setup[30308]: ERROR: Docker has been previously configured for use with devicemapper graph driver. Not creating a new thin pool as existing docker metadata will fail to work with it. Manua
Apr 17 16:36:06 fedora-25-pulp-2-13 docker-storage-setup[30308]: INFO: Docker state can be reset by stopping docker and by removing /var/lib/docker directory. This will destroy existing docker images and containers and all the docker metad
Apr 17 16:36:06 fedora-25-pulp-2-13 systemd[1]: docker-storage-setup.service: Main process exited, code=exited, status=1/FAILURE
Apr 17 16:36:06 fedora-25-pulp-2-13 systemd[1]: Failed to start Docker Storage Setup.
Apr 17 16:36:06 fedora-25-pulp-2-13 systemd[1]: docker-storage-setup.service: Unit entered failed state.
Apr 17 16:36:06 fedora-25-pulp-2-13 systemd[1]: docker-storage-setup.service: Failed with result 'exit-code'.
```

**Comment by Ichimonji10** [comment]
I've added a second commit to this PR:

> pulp-crane role: Let Apache bind to port 5000
>
> Add a task to the pulp-crane role. This new task configures SELinux so
> that Apache can bind to port 5000. This new task is a hack, and it
> exists only because https://pulp.plan.io/issues/2719 has not yet been
> fixed. When that issue is fixed, the hack added by this commit should be
> removed.

It works well. I can now provision usable machines with Crane! This un-blocks other PRs like https://github.com/PulpQE/pulp-smash/pull/624.

**Comment by elyezer** [comment]
Thank you!

**Pull request merged**
